/** Etiquetas en español de las acciones registradas en admin_audit_log. Módulo puro. */
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  crear_usuario: 'Creó un usuario',
  suspender_usuario: 'Suspendió una cuenta',
  reactivar_usuario: 'Reactivó una cuenta',
  extender_trial: 'Extendió un trial',
  activar_suscripcion: 'Activó una suscripción',
  resetear_contrasena: 'Reseteó una contraseña',
  desbloquear_acceso: 'Desbloqueó el acceso de una cuenta',
  desactivar_2fa: 'Desactivó el 2FA de una cuenta',
  editar_cuenta: 'Editó los datos de una cuenta',
  ajustar_limites: 'Ajustó los topes de una cuenta',
  entrar_como: 'Entró como un usuario (impersonación)',
  salir_impersonacion: 'Salió de la impersonación',
  exportar_datos_cuenta: 'Exportó los datos de una cuenta (habeas data)',
  eliminar_cuenta: 'Eliminó una cuenta y sus datos (habeas data)',
  moderar_biblioteca: 'Moderó la biblioteca (sello de revisión)',
  publicar_novedad: 'Publicó una novedad',
  eliminar_novedad: 'Eliminó una novedad',
  crear_organizacion: 'Creó una organización',
  editar_organizacion: 'Editó una organización',
  guardar_preajustes_permisos: 'Guardó plantillas de permisos',
  configurar_proveedor: 'Configuró un proveedor',
  editar_plan: 'Editó un plan',
};
