'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { FolderOpen, RefreshCw, FileCheck2, ExternalLink } from 'lucide-react';
import { Button, Card } from '@/components/ui';
import type { ReceivedConsentPrimitives } from '@/contexts/clinical-records/domain/ReceivedConsent';
import type { ReceptionSettings } from '@/contexts/clinical-records/infrastructure/consent-reception/ConsentReceptionSettings';
import { connectConsentInboxAction, disconnectConsentInboxAction, scanConsentInboxAction, saveConsentFormAction, dismissConsentReceiptAction, reviewConsentReceiptAction } from '@/app/(app)/consentimientos/actions';
export function ConsentInboxPanel({ owner, receipts, settings, patients }: { owner: string; receipts: ReceivedConsentPrimitives[]; settings: ReceptionSettings | null; patients: {id: string; name: string}[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [form, setForm] = useState(settings?.formTemplate ?? '');
  useEffect(() => { const refresh = () => router.refresh(); window.addEventListener('consent-inbox-updated', refresh); return () => window.removeEventListener('consent-inbox-updated', refresh); }, [router]);
  async function run(action: () => Promise<void | false>, message: string) { if (busy) return; setBusy(true); setError(''); setNotice(''); try { if (await action() === false) return; setNotice(message); router.refresh(); window.dispatchEvent(new Event('consent-inbox-rescan')); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo completar la operación.'); } finally { setBusy(false); } }
  async function connect() { await run(async () => { const choose = window.escuchaDesktop?.chooseConsentFolder; if (!choose) throw new Error('Abre esta pantalla desde el programa instalado para elegir la carpeta.'); const proof = await choose(owner); if (!proof) return false; await connectConsentInboxAction(proof); }, 'La carpeta se revisará cada 30 segundos mientras el programa esté abierto.'); }
  const pending = receipts.filter(receipt => receipt.status === 'pendiente'); const history = receipts.filter(receipt => receipt.status !== 'pendiente');
  return <div className="space-y-5">
    <Card><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 font-semibold"><FolderOpen size={20} /> Recepción desde Drive</h2><p className="mt-2 text-sm text-ink-soft">Elige una carpeta privada de Google Drive para escritorio y márcala disponible sin conexión. Usa una carpeta distinta de los respaldos.</p><p className="mt-2 break-all text-sm font-medium">{settings?.folder ?? 'Todavía no hay una carpeta conectada.'}</p></div><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={connect}>{settings ? 'Cambiar carpeta' : 'Conectar carpeta'}</Button>{settings ? <Button variant="outline" disabled={busy} onClick={() => run(async () => { const result = await scanConsentInboxAction(); if (result.unavailable) throw new Error('La carpeta no está disponible. Comprueba Drive y vuelve a intentarlo.'); }, 'Revisión completada. Un archivo nuevo debe permanecer estable en dos revisiones antes de importarse.')}><RefreshCw size={15} /> Revisar ahora</Button> : null}</div></div>{settings ? <button disabled={busy} onClick={() => run(disconnectConsentInboxAction, 'Recepción desconectada. Los documentos guardados se conservan.')} className="mt-3 text-sm text-ink-soft underline">Desconectar recepción</button> : null}<p className="mt-3 text-xs text-ink-soft">PDF, PNG, JPG y WebP · Hasta 20 MB por archivo · Las copias recibidas en Drive son legibles allí; el programa cifra su copia local.</p></Card>
    <details className="rounded-card border border-line bg-surface p-5"><summary className="cursor-pointer font-semibold">Configurar la entrega con Google Forms</summary><div className="mt-4 space-y-3 text-sm"><p>El formulario recibe el documento que el paciente ya firmó. El script lo organiza en Drive con el código de recepción generado desde su expediente.</p><a className="inline-flex items-center gap-1 text-primary underline" href="/google-consent-reception.gs.txt" download>Descargar script de Google Apps Script <ExternalLink size={14} /></a><p>Abre Apps Script en tu cuenta de Google, pega el script y ejecuta <code>crearFormulario</code>. Añade una pregunta «Subir archivo» al formulario y ejecuta <code>conectarRecepcion</code>. El registro mostrará la carpeta y el enlace prellenado.</p><p>Conecta aquí esa carpeta. Para subir archivos, el paciente necesitará una cuenta de Google.</p><label className="block">Enlace prellenado, con <code>CODIGO</code> en el campo de recepción<input aria-label="Enlace prellenado de Google Forms" value={form} onChange={event => setForm(event.target.value)} className="mt-1 w-full rounded-xl border border-line bg-bg p-3" placeholder="https://docs.google.com/forms/d/.../viewform?entry.123=CODIGO" /></label><Button variant="outline" disabled={busy || !settings} onClick={() => run(() => saveConsentFormAction(form), 'Enlace guardado. Puedes preparar la recepción desde el consentimiento de cada paciente.')}>Guardar enlace del formulario</Button><p className="text-xs text-ink-soft">El formulario y el script se autorizan una vez en tu cuenta de Google. Crear la cuenta local del programa no configura este servicio.</p></div></details>
    {error ? <p role="alert" className="rounded-xl bg-danger-soft p-3 text-sm text-danger">{error}</p> : null}{notice ? <p role="status" className="rounded-xl bg-primary-light p-3 text-sm text-primary">{notice}</p> : null}
    <div><h2 className="mb-3 font-semibold">Pendientes de revisión ({pending.length})</h2>{pending.length ? <div className="space-y-3">{pending.map(receipt => <ReceiptReview key={receipt.id} receipt={receipt} patients={patients} busy={busy} run={run} />)}</div> : <Card><p className="text-sm text-ink-soft">Cuando Drive entregue un documento estable aparecerá aquí. También puedes colocar un PDF firmado directamente en la carpeta conectada.</p></Card>}</div>
    {history.length ? <details className="rounded-card border border-line bg-surface p-5"><summary className="cursor-pointer font-semibold">Historial de recepción ({history.length})</summary><div className="mt-3 space-y-3">{history.map(receipt => <div key={receipt.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-line pb-3 text-sm"><div><strong className="break-all">{receipt.document.filename}</strong><p className="text-ink-soft">{receipt.status === 'archivado' ? `Archivado · Firma: ${receipt.signedDate}` : 'Descartado de la bandeja'} · Recibido {new Date(receipt.receivedAt).toLocaleString('es')}</p></div><div className="flex gap-3"><a href={`/consentimientos/${receipt.id}`} className="text-primary underline">Ver documento</a>{receipt.patientId ? <Link href={`/pacientes/${receipt.patientId}`} className="text-primary underline">Paciente</Link> : null}</div></div>)}</div></details> : null}
  </div>;
}
function ReceiptReview({ receipt, patients, busy, run }: { receipt: ReceivedConsentPrimitives; patients: {id:string; name:string}[]; busy:boolean; run: (action:()=>Promise<void>, message:string)=>Promise<void> }) {
  const [patient, setPatient] = useState(receipt.suggestedPatientId ?? ''); const [date, setDate] = useState(''); const [confirmed, setConfirmed] = useState(false);
  return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{patients.find(p => p.id === receipt.suggestedPatientId)?.name ?? "Documento por identificar"}</h3><p className="mt-1 break-all text-xs text-ink-soft">{receipt.document.filename}</p><p className="mt-1 text-xs text-ink-soft">Recibido {new Date(receipt.receivedAt).toLocaleString('es')} · {receipt.suggestedPatientId ? 'Paciente sugerido por el código; confirma la correspondencia.' : 'Sin código reconocido; elige el paciente después de revisar el documento.'}</p></div><a className="inline-flex items-center gap-1 text-sm text-primary underline" href={`/consentimientos/${receipt.id}`}><ExternalLink size={15} /> Abrir documento</a></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Paciente<select aria-label={`Paciente para ${receipt.document.filename}`} className="mt-1 w-full rounded-xl border border-line bg-bg p-2" value={patient} onChange={event => { setPatient(event.target.value); setConfirmed(false); }}><option value="">Seleccionar paciente</option>{patients.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-sm">Fecha de firma del documento<input aria-label={`Fecha de firma para ${receipt.document.filename}`} type="date" value={date} onChange={event => setDate(event.target.value)} max={new Date().toISOString().slice(0,10)} className="mt-1 w-full rounded-xl border border-line bg-bg p-2" /></label></div><label className="mt-3 flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} /> Revisé la firma y confirmé que este documento corresponde al paciente seleccionado.</label><div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy || !patient || !date || !confirmed} onClick={() => run(() => reviewConsentReceiptAction(receipt.id, patient, date, confirmed), 'Documento archivado en el expediente. Se conserva su copia original y la fecha de recepción.')}><FileCheck2 size={16} /> Confirmar y archivar</Button><Button variant="outline" disabled={busy} onClick={() => run(() => dismissConsentReceiptAction(receipt.id), 'Documento retirado de pendientes. Su copia se conserva en el historial.')}>Descartar de la bandeja</Button></div></Card>;
}
