'use client';
import { useState } from 'react';
import Link from 'next/link';
import { prepareConsentReceptionAction } from '@/app/(app)/consentimientos/actions';
export function ConsentReceptionRequest({ patientId }: { patientId: string }) {
  const [result, setResult] = useState<{code:string; link:string} | null>(null); const [error, setError] = useState(''); const [busy,setBusy] = useState(false); const [copied,setCopied] = useState(false);
  async function prepare() { setBusy(true); setError(''); try { setResult(await prepareConsentReceptionAction(patientId)); } catch(e) { setError(e instanceof Error ? e.message : 'No se pudo preparar la recepción.'); } finally { setBusy(false); } }
  async function copy() { try { await navigator.clipboard.writeText(result!.link || result!.code); setCopied(true); } catch { setError('No se pudo copiar. Selecciona el código o enlace y cópialo manualmente.'); } }
  return <div className="mt-4 rounded-xl border border-line bg-bg p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><strong>Recepción con Google Drive</strong><Link href="/consentimientos" className="text-primary underline">Abrir bandeja</Link></div><p className="mt-2 text-ink-soft">Prepara un código para relacionar el documento recibido con este paciente. La firma se revisa antes de archivarlo.</p>{result ? <><code className="mt-2 block select-all break-all text-xs">{result.code}</code>{result.link ? <a className="mt-2 block select-all break-all text-xs text-primary" href={result.link} target="_blank" rel="noreferrer">{result.link}</a> : <p className="mt-2 text-xs text-ink-soft">Configura el formulario en la bandeja o nombra el archivo <code>{result.code}__firmado.pdf</code> al colocarlo en Drive.</p>}<button className="mt-2 font-semibold text-primary" type="button" onClick={copy}>{copied ? 'Copiado' : result.link ? 'Copiar enlace de entrega' : 'Copiar código de recepción'}</button></> : <button type="button" disabled={busy} className="mt-2 font-semibold text-primary" onClick={prepare}>{busy ? 'Preparando…' : 'Preparar recepción'}</button>}{error ? <p role="alert" className="mt-2 text-danger">{error}</p> : null}</div>;
}
