'use client';

import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Check, ChevronRight, Cloud, Code2, Coffee, Download, FileText, FolderHeart, Github, HardDrive, Heart, LayoutDashboard, Menu, Moon, Palette, Play, ShieldCheck, Sun, Users, Wallet, WifiOff, X } from 'lucide-react';
import { LogoMark } from '@/components/Logo';
import { PROJECT_LINKS } from '@/components/project/projectLinks';
import styles from './Showcase.module.css';

const PALETTES = [
  { name: 'Bosque', color: '#22634e', accent: '#cee68f' },
  { name: 'Salvia', color: '#647750', accent: '#dbe3bf' },
  { name: 'Jardín', color: '#288068', accent: '#b5e6c8' },
  { name: 'Océano', color: '#246e85', accent: '#b2dfe9' },
  { name: 'Lavanda', color: '#795b93', accent: '#e2cff7' },
  { name: 'Terracota', color: '#a25638', accent: '#f5d1b8' },
];

const FAQ = [
  ['¿Es gratis de verdad?', 'Sí. La edición para PC no tiene suscripción ni período de prueba. El código propio tiene licencia MIT: puedes estudiarlo, modificarlo y contribuir. El apoyo en Ko-fi es voluntario. Los servicios externos que decidas conectar pueden tener sus propios costos.'],
  ['¿Qué necesito para instalarlo?', 'Una PC con Windows de 64 bits. Descarga el instalador desde las versiones de GitHub, ejecútalo y crea tu cuenta local. El programa incluye su servidor y su base de datos: no necesitas instalar Node.js ni contratar alojamiento. macOS y Linux todavía no tienen un instalador publicado.'],
  ['¿Puedo trabajar sin internet?', 'Sí: agenda, pacientes, expedientes, notas, registro de pagos y lecturas que hayas instalado funcionan en local. Google Drive, Calendar, correo e IA de proveedores necesitan internet y una configuración propia. Los recordatorios locales no se ejecutan con el programa cerrado.'],
  ['¿Cómo continúo en otra PC?', 'Conecta una carpeta de Google Drive para escritorio y crea una contraseña de cifrado. Publica una versión de tu consulta, espera a que Drive la entregue y recíbela en la otra PC con la misma contraseña. Es un intercambio manual de versiones completas: trabaja en una PC a la vez; no fusiona cambios simultáneos. También puedes trasladar un respaldo cifrado.'],
  ['¿Incluye inteligencia artificial, correo y Google Calendar?', 'Son opcionales. Puedes configurar tus claves de OpenAI, Anthropic o Resend. Calendar requiere tu propio cliente OAuth de escritorio y autorización de Google; permite publicar horarios privados y revisar conflictos. La aplicación sigue funcionando sin conectar estos servicios.'],
  ['¿Qué incluye la biblioteca?', 'Un catálogo y lector para tus archivos y publicaciones instaladas. Los libros, publicaciones externas y el catálogo CIE-11 se distribuyen aparte; no están incluidos en el instalador público. Sus licencias son independientes de la licencia del código.'],
];

function ProjectBrand() {
  return <a href="#" className={styles.brand} aria-label="EscuchaInterna, inicio"><LogoMark size={34} /><span>escucha<span className={styles.brandSecond}>interna</span><b>.</b></span></a>;
}

/** Vista ilustrativa, sin conexión a cuentas ni expedientes reales. */
function ProductPreview({ palette = 0, dark = false }: { palette?: number; dark?: boolean }) {
  const [section, setSection] = useState('Inicio');
  const colors = PALETTES[palette];
  const items = [{ name: 'Inicio', icon: LayoutDashboard }, { name: 'Agenda', icon: CalendarDays }, { name: 'Pacientes', icon: Users }, { name: 'Pagos', icon: Wallet }];
  return <div className={styles.preview} data-preview-dark={dark ? 'true' : 'false'} style={{ '--preview-primary': colors.color, '--preview-accent': colors.accent } as React.CSSProperties}>
    <div className={styles.windowBar}><span className={styles.windowDots}><i /><i /><i /></span><span>EscuchaInterna para PC</span><HardDrive size={12} aria-hidden="true" /></div>
    <div className={styles.windowBody}>
      <aside className={styles.previewSidebar}><div className={styles.previewBrand}><LogoMark size={21} /><strong>escuchainterna</strong></div><span className={styles.previewNavLabel}>TU CONSULTA</span>{items.map(({ name, icon: Icon }) => <button key={name} type="button" aria-pressed={section === name} onClick={() => setSection(name)}><Icon size={15} aria-hidden="true" /><span>{name}</span></button>)}<div className={styles.previewSidebarBottom}><BookOpen size={15} aria-hidden="true" /> Biblioteca<br /><span><ShieldCheck size={13} aria-hidden="true" /> Consulta local</span></div></aside>
      <div className={styles.previewContent}>
        <div className={styles.previewBreadcrumb}>Tu consulta <ChevronRight size={12} aria-hidden="true" /> {section}<span className={styles.localBadge}><i /> En esta PC</span></div>
        {section === 'Inicio' || section === 'Agenda' ? <>
          <div className={styles.previewWelcome}><span>UN NUEVO DÍA EN TU CONSULTA</span><h3>{section === 'Inicio' ? 'Más espacio para escuchar.' : 'Tu día, con claridad.'}</h3><p>Lunes · Una vista de ejemplo</p><span className={styles.previewFlower} aria-hidden="true">✳</span></div>
          <div className={styles.previewActions}><span><Users size={16} aria-hidden="true" /> Nuevo paciente</span><span><CalendarDays size={16} aria-hidden="true" /> Agenda de hoy</span><span><BookOpen size={16} aria-hidden="true" /> Biblioteca</span></div>
          <div className={styles.previewAgenda}><div><h4>Tu agenda de hoy</h4><span>Ver agenda <ArrowRight size={12} aria-hidden="true" /></span></div>{[{ time: '09:00', initials: 'AL', label: 'Sesión individual', color: 'green' }, { time: '11:30', initials: 'MC', label: 'Sesión de seguimiento', color: 'purple' }, { time: '15:00', initials: 'JR', label: 'Primera consulta', color: 'warm' }].map(row => <div className={styles.previewBooking} key={row.time}><time>{row.time}</time><span className={styles.previewAvatar} data-color={row.color}>{row.initials}</span><div><strong>{row.label}</strong><small>Paciente de ejemplo · 50 min</small></div><span className={styles.previewStatus}>Agendada</span></div>)}</div>
        </> : section === 'Pacientes' ? <><div className={styles.previewWelcome}><span>CADA HISTORIA, EN SU LUGAR</span><h3>Pacientes y expedientes.</h3><p>Plantillas, notas y documentos a mano.</p></div><div className={styles.previewAgenda}><h4>Vista de ejemplo</h4>{['Paciente de ejemplo A', 'Paciente de ejemplo B', 'Paciente de ejemplo C'].map((name, index) => <div key={name} className={styles.previewBooking}><span className={styles.previewAvatar}>{index + 1}</span><div><strong>{name}</strong><small>Historia clínica · Notas de sesión</small></div><FileText size={17} aria-hidden="true" /></div>)}</div></> : <><div className={styles.previewWelcome}><span>MENOS HOJAS DE CÁLCULO</span><h3>Pagos con perspectiva.</h3><p>Un registro local de tu actividad.</p></div><div className={styles.previewAgenda}><h4>Resumen ilustrativo</h4><div className={styles.previewMetrics}><div><small>Sesiones registradas</small><strong>24</strong></div><div><small>Pagos al día</small><strong>21</strong></div></div><div className={styles.previewChart} aria-hidden="true">{[35, 52, 43, 67, 58, 82, 70, 95].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div></div></>}
        <p className={styles.previewFootnote}>Demostración interactiva · Datos ficticios</p>
      </div>
    </div>
  </div>;
}

export function OpenSourceShowcase() {
  const root = useRef<HTMLDivElement>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const [palette, setPalette] = useState(0);
  const [darkPreview, setDarkPreview] = useState(false);
  const [motionPaused, setMotionPaused] = useState(false);

  useEffect(() => {
    const element = root.current;
    const preference = window.matchMedia('(prefers-reduced-motion: reduce)');
    if (!element || preference.matches || motionPaused || !('IntersectionObserver' in window)) return;
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.setAttribute('data-visible', 'true'); observer.unobserve(entry.target); } }), { threshold: 0.08 });
    element.querySelectorAll('[data-reveal]').forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, [motionPaused]);

  const closeMenu = () => setMenuOpen(false);
  return <div className={styles.showcase} ref={root} data-motion-paused={motionPaused ? 'true' : 'false'}>
    <a href="#contenido" className={styles.skipLink}>Saltar al contenido</a>
    <header className={styles.header}><div className={styles.navInner}><ProjectBrand /><button type="button" className={styles.menuToggle} aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={menuOpen} aria-controls="showcase-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={23} /> : <Menu size={23} />}</button><nav id="showcase-navigation" aria-label="Navegación principal" className={styles.nav} data-open={menuOpen ? 'true' : 'false'}><a href="#aplicacion" onClick={closeMenu}>La aplicación</a><a href="#apariencia" onClick={closeMenu}>A tu manera</a><a href="#proyecto" onClick={closeMenu}>Código abierto</a><a href={PROJECT_LINKS.support} target="_blank" rel="noopener noreferrer" className={styles.navSupport}><Coffee size={15} aria-hidden="true" /> Apoyar</a><a href={PROJECT_LINKS.download} className={styles.navDownload}><Download size={15} aria-hidden="true" /> Descargar</a></nav></div></header>
    <main id="contenido">
      <section className={styles.hero} aria-labelledby="hero-title">
        <div className={styles.heroGlow} aria-hidden="true" /><div className={styles.heroGrid} aria-hidden="true" />
        <div className={styles.heroCopy}><span className={styles.eyebrow}><i /> SOFTWARE LIBRE · HECHO PARA PSICÓLOGOS</span><h1 id="hero-title">Tu consulta.<br />Tu PC.<br /><span>Tu tranquilidad.</span></h1><p>Un espacio para organizar tu práctica y concentrarte en lo que importa: escuchar. Gratis, de código abierto y con tus datos en tu equipo.</p><div className={styles.heroButtons}><a href={PROJECT_LINKS.download} className={styles.buttonPrimary}><Download size={19} aria-hidden="true" /> Descargar para Windows <ArrowUpRight size={17} aria-hidden="true" /></a><a href={PROJECT_LINKS.repository} className={styles.buttonSecondary}><Github size={19} aria-hidden="true" /> Ver el código</a></div><span className={styles.heroMeta}>Windows de 64 bits <span>·</span> Licencia MIT <span>·</span> Sin suscripción</span><a href="#aplicacion" className={styles.heroExplore}><span><ArrowDown size={16} aria-hidden="true" /></span> Descubre tu nuevo espacio de trabajo</a></div>
        <div className={styles.heroProduct}><div className={styles.heroOrbit} aria-hidden="true" /><ProductPreview /><div className={`${styles.floatingNote} ${styles.offlineNote}`}><span><WifiOff size={19} aria-hidden="true" /></span><div><strong>Internet puede esperar.</strong><small>Tu consulta sigue funcionando.</small></div></div><div className={`${styles.floatingNote} ${styles.privacyNote}`}><ShieldCheck size={19} aria-hidden="true" /><span>Tus datos se quedan contigo.</span></div></div>
      </section>

      <div className={styles.principles} aria-label="Beneficios principales"><span><HardDrive size={20} aria-hidden="true" /> Primero, tu PC</span><span><WifiOff size={20} aria-hidden="true" /> Funciona sin conexión</span><span><Code2 size={20} aria-hidden="true" /> Código que puedes explorar</span><span><Heart size={20} aria-hidden="true" /> Apoyo voluntario</span></div>

      <section id="aplicacion" className={styles.section} aria-labelledby="app-title">
        <div className={styles.sectionHeading} data-reveal><div><span className={styles.kicker}>MENOS RUIDO. MÁS CONSULTA.</span><h2 id="app-title">Todo encuentra<br /><span>su lugar.</span></h2></div><p>De la primera cita a la siguiente sesión. Las herramientas de tu día a día, juntas en una aplicación que abre en tu PC.</p></div>
        <div className={styles.bento}>
          <article className={`${styles.bentoCard} ${styles.agendaCard}`} data-reveal><div className={styles.cardIcon}><CalendarDays size={25} aria-hidden="true" /></div><h3>Una agenda que da aire.</h3><p>Organiza horarios, disponibilidad y sesiones. Cambia entre vistas de calendario para entender tu día de un vistazo.</p><div className={styles.calendarArt} aria-hidden="true"><div><span>L</span><span>M</span><span>X</span><span>J</span><span>V</span></div><div className={styles.calendarCells}>{Array.from({length: 15}, (_, i) => <span key={i} className={[2, 7, 10].includes(i) ? styles.calendarBooked : ''}>{[2, 7, 10].includes(i) ? <><i />Sesión</> : ''}</span>)}</div></div><span className={styles.cardLabel}>AGENDA Y DISPONIBILIDAD</span></article>
          <article className={`${styles.bentoCard} ${styles.recordsCard}`} data-reveal><div className={styles.cardIcon}><FolderHeart size={25} aria-hidden="true" /></div><h3>Cada historia merece cuidado.</h3><p>Pacientes, historias clínicas con plantillas, notas de sesión y archivos. Un hilo para seguir cada proceso.</p><div className={styles.recordArt} aria-hidden="true"><span><FileText size={17} /> Historia clínica <Check size={15} /></span><span><FileText size={17} /> Nota de sesión <Check size={15} /></span><span><FolderHeart size={17} /> Documentos <ChevronRight size={15} /></span></div><span className={styles.cardLabel}>PACIENTES Y EXPEDIENTES</span></article>
          <article className={`${styles.bentoCard} ${styles.paymentsCard}`} data-reveal><Wallet size={25} aria-hidden="true" /><h3>Más claridad en tus pagos.</h3><p>Registra cobros y consulta el resumen de tu actividad, sin otra hoja de cálculo.</p><span className={styles.cardLabel}>REGISTRO LOCAL</span></article>
          <article className={`${styles.bentoCard} ${styles.libraryCard}`} data-reveal><BookOpen size={25} aria-hidden="true" /><h3>Lecturas a mano.</h3><p>Organiza tu catálogo y lee los libros y publicaciones que instales en cada equipo.</p><span className={styles.cardLabel}>BIBLIOTECA Y LECTOR</span></article>
        </div>
        <details className={styles.realCapture}><summary><LayoutDashboard size={17} aria-hidden="true" /> Ver una captura real del programa <span aria-hidden="true">+</span></summary><figure><Image src="/showcase/programa.webp" width={1440} height={940} sizes="(max-width: 600px) 100vw, 1200px" alt="Pantalla de inicio de EscuchaInterna para PC, con accesos a pacientes, agenda y biblioteca, en una instalación de prueba vacía." /><figcaption>Captura de una instalación de prueba. Sin información real de pacientes.</figcaption></figure></details>
      </section>

      <section className={styles.controlSection} aria-labelledby="control-title"><div className={styles.controlCopy} data-reveal><span className={styles.kicker}>LOCAL POR CONVICCIÓN</span><h2 id="control-title">Tu trabajo.<br /><span>Bajo tu control.</span></h2><p>Abre el programa y sigue con tu consulta. Sin contratar un servidor para comenzar, sin una cuota mensual para acceder a tus expedientes.</p><ul><li><Check size={18} aria-hidden="true" /><span><strong>Trabaja sin conexión.</strong> Tus herramientas principales viven en el equipo.</span></li><li><Check size={18} aria-hidden="true" /><span><strong>Conserva una copia.</strong> Crea y restaura respaldos cifrados con contraseña.</span></li><li><Check size={18} aria-hidden="true" /><span><strong>Elige qué conectas.</strong> Correo, IA y Calendar son servicios opcionales con configuración propia.</span></li></ul></div><div className={styles.controlVisual} data-reveal><div className={styles.connectionLine} aria-hidden="true" /><div className={styles.deviceCard}><HardDrive size={34} aria-hidden="true" /><strong>Tu PC</strong><small>Consulta y archivos locales</small><span><ShieldCheck size={14} aria-hidden="true" /> Contenido clínico cifrado</span></div><div className={styles.driveCard}><Cloud size={25} aria-hidden="true" /><div><strong>Otra PC, el mismo espacio.</strong><p>Publica y recibe versiones cifradas con Google Drive para escritorio.</p><a href={`${PROJECT_LINKS.repository}/blob/main/docs/desktop-sync.md`}>Cómo funciona <ArrowUpRight size={14} aria-hidden="true" /></a></div></div><p className={styles.controlNote}>Tú decides cuándo transferir. Drive entrega las versiones; la app no combina cambios simultáneos.</p></div></section>

      <section id="apariencia" className={`${styles.section} ${styles.appearanceSection}`} aria-labelledby="appearance-title"><div className={styles.sectionHeading} data-reveal><div><span className={styles.kicker}>UN POCO MÁS TUYO</span><h2 id="appearance-title">También puede<br /><span>sentirse como tú.</span></h2></div><p>Seis paletas, modo día, noche o automático. Colores para encontrar tu ritmo y movimiento que respeta tus preferencias.</p></div><div className={styles.appearanceDemo} data-reveal><div className={styles.appearanceControls}><h3>Prueba una combinación.</h3><p>Esta vista cambia aquí mismo.<br />Tu consulta se configura dentro del programa.</p><div className={styles.swatches} role="group" aria-label="Paleta de la demostración">{PALETTES.map((theme, i) => <button type="button" key={theme.name} onClick={() => setPalette(i)} aria-label={theme.name} aria-pressed={palette === i} style={{ '--swatch': theme.color } as React.CSSProperties}><span>{palette === i ? <Check size={17} aria-hidden="true" /> : null}</span><small>{theme.name}</small></button>)}</div><div className={styles.modeSwitch} role="group" aria-label="Modo de la demostración"><button type="button" aria-pressed={!darkPreview} onClick={() => setDarkPreview(false)}><Sun size={16} aria-hidden="true" /> Día</button><button type="button" aria-pressed={darkPreview} onClick={() => setDarkPreview(true)}><Moon size={16} aria-hidden="true" /> Noche</button></div><div className={styles.appearanceTip}><Palette size={19} aria-hidden="true" /><span>Pequeños detalles.<br /><strong>Un espacio más cómodo.</strong></span></div></div><div className={styles.themePreview}><ProductPreview palette={palette} dark={darkPreview} /></div></div></section>

      <section id="proyecto" className={styles.openSection} aria-labelledby="open-title"><div className={styles.openArtwork} aria-hidden="true"><span>{'{ '}</span><Heart size={74} strokeWidth={1.4} /><span>{' }'}</span><small>MIT · HECHO PARA COMPARTIR</small></div><div data-reveal><span className={styles.kicker}>ABIERTO DESDE EL CÓDIGO</span><h2 id="open-title">Las buenas herramientas<br />crecen en comunidad.</h2><p>EscuchaInterna es un proyecto que puedes usar, estudiar y mejorar. El código está en GitHub, con licencia MIT. Tu experiencia también puede darle forma.</p><div className={styles.contributionLinks}><a href={PROJECT_LINKS.repository}><Github size={18} aria-hidden="true" /> Explorar el repositorio <ArrowUpRight size={15} aria-hidden="true" /></a><a href={PROJECT_LINKS.issues}>Proponer una mejora <ArrowUpRight size={15} aria-hidden="true" /></a></div><div className={styles.openFacts}><span><Code2 size={15} aria-hidden="true" /> Código accesible</span><a href={PROJECT_LINKS.license}>Licencia MIT <ArrowUpRight size={13} aria-hidden="true" /></a><span>Desarrollo en evolución</span></div></div></section>

      <section id="empezar" className={`${styles.section} ${styles.stepsSection}`} aria-labelledby="steps-title"><div className={styles.sectionHeading} data-reveal><div><span className={styles.kicker}>DE AQUÍ A TU ESCRITORIO</span><h2 id="steps-title">Empieza con calma.<br /><span>En tres pasos.</span></h2></div><a href={PROJECT_LINKS.guide} className={styles.textLink}>Ver la guía de instalación <ArrowUpRight size={16} aria-hidden="true" /></a></div><ol className={styles.steps}><li data-reveal><span>01</span><Download size={24} aria-hidden="true" /><h3>Descarga.</h3><p>Encuentra el instalador para Windows de 64 bits en las versiones de GitHub.</p></li><li data-reveal><span>02</span><HardDrive size={24} aria-hidden="true" /><h3>Abre tu espacio.</h3><p>Instala el programa y crea una cuenta local. Todo lo necesario viene en el instalador.</p></li><li data-reveal><span>03</span><Heart size={24} aria-hidden="true" /><h3>Hazlo tuyo.</h3><p>Elige tu tema, organiza tu agenda y guarda tu primer respaldo. A tu ritmo.</p></li></ol></section>

      <section id="preguntas" className={`${styles.section} ${styles.faqSection}`} aria-labelledby="faq-title"><div><span className={styles.kicker}>ANTES DE EMPEZAR</span><h2 id="faq-title">Con las cosas<br /><span>claras.</span></h2><p>Lo esencial sobre esta edición para PC.</p></div><div className={styles.faqList}>{FAQ.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>

      <section id="apoyar" className={styles.supportSection} aria-labelledby="support-title"><div className={styles.coffeeArt} aria-hidden="true"><Coffee size={68} strokeWidth={1.4} /><Heart size={19} className={styles.coffeeHeart} /></div><div><span className={styles.kicker}>UN CAFÉ TAMBIÉN CONSTRUYE</span><h2 id="support-title">Si te sirve, ayúdalo a crecer.</h2><p>Detrás del código hay tiempo, cuidado y ganas de hacerlo mejor. Puedes apoyar a Laroc en Ko-fi para acompañar el desarrollo de EscuchaInterna.</p><span>Voluntario, siempre. El programa sigue siendo gratuito.</span></div><a href={PROJECT_LINKS.support} target="_blank" rel="noopener noreferrer" className={styles.buttonCoffee}><Coffee size={19} aria-hidden="true" /> Invítame a un café <ArrowUpRight size={17} aria-hidden="true" /></a></section>

      <section className={styles.finalSection} aria-labelledby="final-title"><span className={styles.eyebrow}><i /> TU NUEVO ESPACIO DE TRABAJO</span><h2 id="final-title">Más atención.<br /><span>Menos distracciones.</span></h2><p>Haz espacio para tu consulta. Lo demás, organízalo aquí.</p><a href={PROJECT_LINKS.download} className={styles.buttonPrimary}><Download size={19} aria-hidden="true" /> Descargar EscuchaInterna <ArrowUpRight size={17} aria-hidden="true" /></a><small>Para Windows de 64 bits · Gratis · Código abierto</small></section>
    </main>
    <footer className={styles.footer}><div className={styles.footerTop}><div><ProjectBrand /><p>Hecho para escuchar mejor.<br />Construido para compartir.</p></div><div><strong>Programa</strong><a href={PROJECT_LINKS.download}>Descargar para Windows</a><a href={PROJECT_LINKS.releases}>Versiones y novedades</a><a href={PROJECT_LINKS.guide}>Guía de instalación</a></div><div><strong>Comunidad</strong><a href={PROJECT_LINKS.repository}>GitHub</a><a href={PROJECT_LINKS.issues}>Errores y propuestas</a><a href={PROJECT_LINKS.support} target="_blank" rel="noopener noreferrer">Ko-fi de Laroc ↗</a></div><div><strong>Proyecto</strong><a href={PROJECT_LINKS.license}>Licencia MIT</a><a href="/legal/privacidad">Privacidad de la web</a><a href="/legal/terminos">Condiciones de uso</a><a href="/login">Acceso web existente</a></div></div><div className={styles.footerBottom}><span>© {new Date().getFullYear()} EscuchaInterna · Código propio bajo licencia MIT</span><button type="button" aria-pressed={motionPaused} onClick={() => setMotionPaused(!motionPaused)}>{motionPaused ? <Play size={13} aria-hidden="true" /> : <span aria-hidden="true">Ⅱ</span>}{motionPaused ? 'Activar animaciones' : 'Pausar animaciones'}</button><a href="#">Volver arriba ↑</a></div></footer>
  </div>;
}
